pipeline:
    publish:
        image: plugins/docker
        registry: registry.hakloev.no
        repo: hakloevno/frontend
        tags:
            - latest
        when:
            branch: master
