pipeline:
    publish:
        image: plugins/docker
        repo: registry.hakloev.no/hakloevno/frontend
        debug: true
        tags:
            - latest
        when:
            branch: master
